### 1.3 Pokemon Types

The types of pokemon are essential in team building as the pokemon's types dictate to which other types a pokemon is weak to and which moves would be more potent for that pokemon to use. 

The types however, were changed during two instances of the entire pokemon franchise which is during Generation 2 with the introduction of dark and steel and at generation 6 with the introduction of fairy. 

Since the analysis only focuses on the format of Generation 5 Overused, the types will be only updated as of Generation 2. The data is gathered from the pokemon fandom website with the following links: 

- [Generation 1 Pokemon Types](https://pokemon.fandom.com/wiki/List_of_Generation_I_Pokémon)

- [Generation 2 Pokemon Types](https://pokemon.fandom.com/wiki/List_of_Generation_II_Pokémon)

- [Generation 3 Pokemon Types](https://pokemon.fandom.com/wiki/List_of_Generation_III_Pokémon)

- [Generation 4 Pokemon Types](https://pokemon.fandom.com/wiki/List_of_Generation_IV_Pokémon)

- [Generation 5 Pokemon Types](https://pokemon.fandom.com/wiki/List_of_Generation_V_Pokémon)

In each generation, the References section is used to correct the typings of the pokemon to fit the fifth generation of games. The data is gathered through copying the table data into a spreadsheet and saving it as a csv after the type correction is applied.

In [ ]:
gen5_types_df = pd.read_csv("./dataset/pokemon-fandom/pokemon_gen5_types.csv")
gen5_types_df

In [ ]:
gen5_types_df.info()

#### 3.1.2 Pokemon's Multiple Forms

Some Pokémon possess multiple forms, each with distinct base stats and typings, and these forms are often notated differently within the dataset. To ensure accuracy and consistency, we carefully reviewed the datasets manually and corrected the entries so that each form is properly represented with its unique base stats and typings. This process helps prevent data inconsistencies and ensures that analyses reflect the true characteristics and potential of each Pokémon form, rather than treating them as a single, generic entity. As a result, our dataset provides a more precise and reliable foundation for any subsequent analysis or modeling.

<p align="center">
  <img src="assets/wormadam.png" alt="Wormadams" width="300">
  <br>
  <em><b>Figure 1.</b> Different Wormadam Forms</em>
</p>

In [ ]:
gen5_types_df.drop('#', axis=1, inplace=True)

In [ ]:
gen5_consolidated_df = pd.merge(gen5_types_df, gen5_stats_df, on='Name', how='outer')
gen5_consolidated_df[gen5_consolidated_df['Type 1'].isna()]

,Name,Type 1,Type 2,Pokedex number,HP,Attack,Special Attack,Defense,Special Defense,Speed,Stat total,Stat average
114,Darmanitan-Zen,NaN,NaN,555,105,30,105,140,105,55,540,90.00
121,Deoxys-Attack,NaN,NaN,386,50,180,20,180,20,150,600,100.00
122,Deoxys-Defense,NaN,NaN,386,50,70,160,70,160,90,600,100.00
123,Deoxys-Speed,NaN,NaN,386,50,95,90,95,90,180,600,100.00
196,Gastrodon-East,NaN,NaN,423,111,83,68,92,82,39,475,79.17
204,Giratina-Origin,NaN,NaN,487,150,120,100,120,100,90,680,113.33
274,Keldeo-Resolute,NaN,NaN,647,91,72,90,129,90,108,580,96.67
289,Kyurem-Black,NaN,NaN,646,125,170,100,120,90,95,700,116.67
290,Kyurem-White,NaN,NaN,646,125,120,90,170,100,95,700,116.67
294,Landorus-Therian,NaN,NaN,645,89,145,90,105,80,91,600,100.00
355,Meloetta-Pirouette,NaN,NaN,648,100,128,90,77,77,128,600,100.00
473,Rotom-Fan,NaN,NaN,479,50,65,107,105,107,86,520,86.67
474,Rotom-Frost,NaN,NaN,479,50,65,107,105,107,86,520,86.67
475,Rotom-Heat,NaN,NaN,479,50,65,107,105,107,86,520,86.67
476,Rotom-Mow,NaN,NaN,479,50,65,107,105,107,86,520,86.67
477,Rotom-Wash,NaN,NaN,479,50,65,107,105,107,86,520,86.67
506,Shaymin-Sky,NaN,NaN,492,100,103,75,120,75,127,600,100.00
585,Thundurus-Therian,NaN,NaN,642,79,105,70,145,80,101,580,96.67
594,Tornadus-Therian,NaN,NaN,641,79,100,80,110,90,121,580,96.67
655,Wormadam-Sandy,NaN,NaN,413,60,79,105,59,85,36,424,70.67
656,Wormadam-Trash,NaN,NaN,413,60,69,95,69,95,36,424,70.67

From the results of the code we can see several Pokemon without a type and this is because the data from Pokemon-Fandom does not include these types, as such these will be modified manually in the file  `pokemon_gen5_types.csv` to accomodate for the missing typing.

In [ ]:
gen5_types_df = pd.read_csv("./dataset/pokemon-fandom/pokemon_gen5_types_fixed.csv")
gen5_types_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 670 entries, 0 to 669
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   #       670 non-null    int64
 1   Name    670 non-null    object
 2   Type 1  670 non-null    object
 3   Type 2  312 non-null    object
dtypes: int64(1), object(3)
memory usage: 21.1+ KB

In [ ]:
multiple_form_pokemon = [
    "Darmanitan-Zen", "Deoxys-Attack", "Deoxys-Defense", "Deoxys-Speed",
    "Gastrodon-East", "Giratina-Origin", "Keldeo-Resolute", "Kyurem-Black", "Kyurem-White",
    "Landorus-Therian", "Meloetta-Pirouette", "Rotom-Fan", "Rotom-Frost", "Rotom-Heat",
    "Rotom-Mow", "Rotom-Wash", "Shaymin-Sky", "Thundurus-Therian", "Tornadus-Therian",
    "Wormadam-Sandy", "Wormadam-Trash"
]
gen5_types_df[gen5_types_df['Name'].isin(multiple_form_pokemon)]

       #                Name    Type 1    Type 2
386  386       Deoxys-Attack   Psychic       NaN
387  386      Deoxys-Defense   Psychic       NaN
388  386        Deoxys-Speed   Psychic       NaN
416  413      Wormadam-Sandy       Bug    Ground
417  413      Wormadam-Trash       Bug     Steel
428  423      Gastrodon-East     Water    Ground
485  479           Rotom-Fan  Electric    Flying
486  479         Rotom-Frost  Electric       Ice
487  479          Rotom-Heat  Electric      Fire
488  479           Rotom-Mow  Electric     Grass
489  479          Rotom-Wash  Electric     Water
498  487     Giratina-Origin     Ghost    Dragon
504  492         Shaymin-Sky     Grass    Flying
568  555      Darmanitan-Zen      Fire   Psychic
655  641    Tornadus-Therian    Flying       NaN
657  642   Thundurus-Therian  Electric    Flying
661  645    Landorus-Therian    Ground    Flying
663  646        Kyurem-Black    Dragon       Ice
664  646        Kyurem-White    Dragon       Ice
666  647     Keldeo-Resolute     Water  Fighting
668  648  Meloetta-Pirouette    Normal  Fighting

In [ ]:
gen5_types_df = pd.read_csv("./dataset/pokemon-fandom/pokemon_gen5_types.csv")
gen5_types_df

       #        Name  Type 1    Type 2
0      1   Bulbasaur   Grass    Poison
1      2     Ivysaur   Grass    Poison
2      3    Venusaur   Grass    Poison
3      4  Charmander    Fire       NaN
4      5  Charmeleon    Fire       NaN
..   ...         ...     ...       ...
646  645    Landorus  Ground    Flying
647  646      Kyurem  Dragon       Ice
648  647      Keldeo   Water  Fighting
649  648    Meloetta  Normal   Psychic
650  649    Genesect     Bug     Steel

[651 rows x 4 columns]

In [ ]:
gen5_types_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 651 entries, 0 to 650
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   #       651 non-null    int64
 1   Name    651 non-null    object
 2   Type 1  651 non-null    object
 3   Type 2  297 non-null    object
dtypes: int64(1), object(3)
memory usage: 20.5+ KB